# Spring Security
api.security.token.secret=${JWT_SECRET:my-secret-key}
api.security.token.expiration=${JWT_EXPIRATION:2}
api.security.token.issuer=${JWT_ISSUER:cinema-api}
api.security.refresh.expiration=${JWT_REFRESH_EXPIRATION:60}
login.max-attempts=3
login.lock-duration-minutes=15

# Spring Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= ${email}
spring.mail.password= ${email_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Admin user
app.admin.username=admin
app.admin.password=senhaSuperSecreta456
app.admin.nome=Administrador Padrão
app.admin.email=admin@meuapp.com