# Swagger
springdoc.swagger-ui.enabled=false

# Database (PROD)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Security / JWT
api.security.token.secret=${JWT_SECRET}
api.security.token.expiration=${JWT_EXPIRATION}
api.security.refresh.expiration=${JWT_REFRESH_EXPIRATION}
api.security.token.issuer=cinema-api
login.max-attempts=3
login.lock-duration-minutes=15

# Admin user
app.admin.username=${ADMIN_USERNAME}
app.admin.password=${ADMIN_PASSWORD}
app.admin.nome=${ADMIN_NAME}
app.admin.email=${ADMIN_EMAIL}
app.admin.cpf=${ADMIN_CPF}

# Cache (PROD - Redis)
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
cache.ttl.genres=${CACHE_TTL_GENRES:86400}
cache.ttl.movies=${CACHE_TTL_MOVIES:21600}
cache.ttl.rooms=${CACHE_TTL_ROOMS:604800}
cache.ttl.standard=${CACHE_TTL_STANDARD:3600}
cache.ttl.short=${CACHE_TTL_SHORT:600}

# Mail (PROD)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logs (PROD)
logging.file.path=/var/log/cinema-api
logging.file.name=application.log
logging.level.root=INFO

# API Mercado Pago
mercadopago.access.token=${MP_ACCESS_TOKEN}

# Intervalo em ms para expiracao automatica de reservas
seat.reservation.expiration.fixed-rate-ms=${SEAT_RESERVATION_EXPIRATION_FIXED_RATE_MS:60000}

# Hash Secret
security.hash.secret=${HASH_SECRET}

cinereserve.payment.pix.expiration-minutes=30